FROM python:3.9.2
ARG USERNAME
ARG PASSWORD
ARG USER_UID
ARG USER_GID
ARG DEBIAN_FRONTEND=noninteractive
ENV DEBIAN_FRONTEND=noninteractive
USER root
RUN apt update && \
    apt install -y -o Dpkg::Options::=--force-confdef \
    curl git unzip xz-utils zip wget less bzip2 ssh
RUN echo "root:${PASSWORD}" | chpasswd
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME
RUN echo "${USERNAME}:${PASSWORD}" | chpasswd
USER $USERNAME
WORKDIR "/home/${USERNAME}"
VOLUME [ "/home/${USERNAME}/.cache/pip"]
# RUN echo "test -e /home/${USERNAME}/projeto/iniciar_venv.sh && /home/${USERNAME}/projeto/iniciar_venv.sh" >> /home/${USERNAME}/.bashrc
CMD [ "sleep", "infinity" ]